CREATE TABLE electronic_journal (
    id SERIAL PRIMARY KEY,
    data_post DATE NOT NULL,
    Fab TEXT NOT NULL,
    №adm_material INTEGER NOT NULL, 
    №stati VARCHAR(255) NOT NULL,
    vid_exp INTEGER NOT NULL,
    stat INTEGER NOT NULL,
    iz_nix INTEGER NOT NULL,
    category INTEGER NOT NULL,
    organ VARCHAR(255) NOT NULL,
    region INTEGER NOT NULL,
    name_organ VARCHAR(255) NOT NULL,
    name_naznch VARCHAR(255) NOT NULL,
    second_name_naznch VARCHAR(255) NOT NULL,
    patronymic_naznch VARCHAR(255),
    name_exp VARCHAR(255) NOT NULL,
    second_name_exp VARCHAR(255) NOT NULL,
    patronymic_exp VARCHAR(255),
    category_diff INTEGER NOT NULL,
    question_count INTEGER NOT NULL,
    object_count INTEGER NOT NULL,
    srok_exp INTEGER,
    stop_date DATE,
    stop_reason TEXT,
    resuming_date DATE,
    srok_resuming INTEGER,
    end_date DATE,
    day_count INTEGER,
    exp_day_count INTEGER,
    exp_res INTEGER,
    cat_vivod INTEGER,
    possible_vivod INTEGER,
    impossible_vivod INTEGER,
    hour_count INTEGER,
    expert_cost FLOAT,
    material_cost FLOAT,
    exploitation_cost FLOAT,
    full_cost FLOAT,
    full_cost_nds FLOAT,
    descrip TEXT,
    is_closed BOOLEAN DEFAULT FALSE
);

CREATE INDEX idx_filenames_is_closed ON electronic_journal(is_closed);