ALTER TABLE users 
DROP COLUMN IF EXISTS first_name VARCHAR(255),
DROP COLUMN IF EXISTS last_name VARCHAR(255),
DROP COLUMN IF EXISTS email VARCHAR(255) UNIQUE,
DROP COLUMN IF EXISTS phone VARCHAR(50);